version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

#  mongo-client:
#    image: mongoclient/mongoclient
#    ports:
#    - 3030:3000
#    environment:
#      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
#    links:
#      - mongo

  web:
    build: .
    links:
      - mongo
    ports:
     - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test

